apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # ...
  annotations:
      gitlab.com/project-id: 'project-id' #1234. This must be in quotes and can be found under Settings --> General
      or
      gitlab.com/project-slug: 'project-slug' # group_name/project_name
spec:
  type: service
  lifecycle: production
  owner: rearportal
  system: sample-system
  dependsOn:
    - Resource:sample-resource
    - Component:nishkarshraj
  providesApis:
    - hello-world
    - petstore
  consumesApis:
    - starwars-graphql
    - streetlights
